[project]
name = "broadcast-transaction"
authors = ["Transaction Broadcast Team"]
description = "A Clarity smart contract for efficient and secure transaction broadcasting"
telemetry = false
requirements = []
[contracts.transaction-broadcaster]
path = "contracts/transaction-broadcaster.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
